config/routes.rb
Rails.application.routes.draw do
  resources :dounuts

  get '/about'=> 'dounuts#about'

  root'dounuts#home'

end

app/models/dounut.rb
class Dounut < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dounuts_controller.rb
class DounutsController < ApplicationController
  before_action :set_dounut, only: [:show, :edit, :update, :destroy]

  def home
  end
  # GET /dounuts.json

  def about
  end


  def index
    @dounuts = Dounut.all
  end

  # GET /dounuts/1
  # GET /dounuts/1.json
  def show
  end

  # GET /dounuts/new
  def new
    @dounut = Dounut.new
  end

  # GET /dounuts/1/edit
  def edit
  end

  # POST /dounuts
  # POST /dounuts.json
  def create
    @dounut = Dounut.new(dounut_params)

    respond_to do |format|
      if @dounut.save
        format.html { redirect_to @dounut, notice: 'Dounut was successfully created.' }
        format.json { render :show, status: :created, location: @dounut }
      else
        format.html { render :new }
        format.json { render json: @dounut.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dounuts/1
  # PATCH/PUT /dounuts/1.json
  def update
    respond_to do |format|
      if @dounut.update(dounut_params)
        format.html { redirect_to @dounut, notice: 'Dounut was successfully updated.' }
        format.json { render :show, status: :ok, location: @dounut }
      else
        format.html { render :edit }
        format.json { render json: @dounut.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dounuts/1
  # DELETE /dounuts/1.json
  def destroy
    @dounut.destroy
    respond_to do |format|
      format.html { redirect_to dounuts_url, notice: 'Dounut was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dounut
      @dounut = Dounut.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dounut_params
      params.require(:dounut).permit(:name, :topping, :topping, :cost, :image)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dounuts_helper.rb
module DounutsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/dounuts/_form.html.erb
<%= form_for(@dounut) do |f| %>
  <% if @dounut.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dounut.errors.count, "error") %> prohibited this dounut from being saved:</h2>

      <ul>
      <% @dounut.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :topping %><br>
    <%= f.text_area :topping %>
  </div>
  <div class="field">
    <%= f.label :topping %><br>
    <%= f.text_area :topping %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.number_field :cost %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dounuts/about.html.erb
<h1>My About page!</h1>

app/views/dounuts/edit.html.erb
<h1>Editing Dounut</h1>

<%= render 'form' %>

<%= link_to 'Show', @dounut %> |
<%= link_to 'Back', dounuts_path %>

app/views/dounuts/home.html.erb
<div class="jumbotron">

	<center>
		<h1>Welcome to the Donut NUT!</h1>

		<img src="http://media-cdn.tripadvisor.com/media/photo-s/03/d6/4e/a8/fractured-prune.jpg">
		<br>

		<%= link_to "Check out our Dounuts!", dounuts_path, class: "btn btn-default" %>
	</center>
</div>

app/views/dounuts/index.html.erb
<h1>All of our Donuts's</h1>
<div class="row">
<% @dounuts.each do |dounuts| %>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img src="<%= dounuts.image %>">
      <div class="caption">
        <h3><%= dounuts.name %></h3>
        <h3>Cost: $<%= dounuts.cost %></h3>
        <%= link_to "More Info", dounuts, class: "btn btn-default" %>
      </div>
    </div>
  </div>
  <% end %>
</div>

<br>

<%= link_to 'New Dounuts', new_dounut_path, class: "btn btn-primary" %>

app/views/dounuts/new.html.erb
<h1>New Dounut</h1>

<%= render 'form' %>

<%= link_to 'Back', dounuts_path %>

app/views/dounuts/show.html.erb
<div class="jumbotron">
  <center>
    <h1><%= @dounuts.name %></h1>
    <img src="<%= @dounuts.image %>">
  </center>
  <h3>Crust: <%= @dounuts.crust %></h3>
  <h3>Sauce: <%= @dounuts.sauce %></h3>
  <h3>Toppings: <%= @dounuts.toppings %></h3>
  <h3>Cost: $<%= @dounuts.cost %></h3>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>DonutShop</title>

  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootswatch/3.0.2/united/bootstrap.min.css">
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.0.2/css/font-awesome.min.css">

  <style>
    /* Only necessary if you are using navbar-fixed-top */
    body {
      padding-top: 50px;
    }
  </style>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to Rails.application.class.parent_name, root_url, :class => "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Donuts", dounuts_url %></li>
        
        <li><a href="about">About</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>

  <div class="container">
    <% if notice.present? %>
      <div class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= notice %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron">

	<center>
		<h1>Welcome to the Dounut NUT!</h1>

		<img src="http://media-cdn.tripadvisor.com/media/photo-s/03/d6/4e/a8/fractured-prune.jpg">
		<br>

		<%= link_to "Check out our Dounuts!", pizza_path, class "btn btn-default" %>
	</center>
</div>